-- XP Blog Supabase setup
-- Run this in the Supabase SQL editor for a fresh project.
-- After creating your auth user, run the owner bootstrap statement near the end.

begin;

create table if not exists public.site_owners (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 50),
  slug text not null check (char_length(slug) between 1 and 80),
  parent_id bigint references public.categories(id) on delete restrict,
  description text,
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_parent_is_not_self check (parent_id is null or parent_id <> id)
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 200),
  content text not null,
  category_id bigint not null references public.categories(id) on delete restrict,
  author_email text not null,
  images jsonb check (images is null or jsonb_typeof(images) = 'array'),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Migration helpers for older versions of this app.
alter table public.posts
  add column if not exists category_id bigint references public.categories(id) on delete restrict;

alter table public.posts
  add column if not exists images jsonb;

alter table public.posts
  add column if not exists created_by uuid references auth.users(id) on delete set null;

alter table public.posts
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists categories_slug_lower_unique
  on public.categories (lower(slug));

create unique index if not exists categories_parent_name_unique
  on public.categories (coalesce(parent_id, 0), lower(name));

create index if not exists categories_parent_id_idx
  on public.categories (parent_id);

create index if not exists categories_sort_idx
  on public.categories (sort_order, name);

create index if not exists posts_category_id_idx
  on public.posts (category_id);

create index if not exists posts_created_at_idx
  on public.posts (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_categories_updated_at on public.categories;
create trigger set_categories_updated_at
before update on public.categories
for each row
execute function public.set_updated_at();

drop trigger if exists set_posts_updated_at on public.posts;
create trigger set_posts_updated_at
before update on public.posts
for each row
execute function public.set_updated_at();

create or replace function public.is_site_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.site_owners
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_site_owner() from public;
grant execute on function public.is_site_owner() to anon, authenticated;

alter table public.site_owners enable row level security;
alter table public.categories enable row level security;
alter table public.posts enable row level security;

drop policy if exists "Visible categories are readable by everyone" on public.categories;
create policy "Visible categories are readable by everyone"
on public.categories
for select
to anon, authenticated
using (is_visible = true or public.is_site_owner());

drop policy if exists "Site owners can create categories" on public.categories;
create policy "Site owners can create categories"
on public.categories
for insert
to authenticated
with check (public.is_site_owner() and created_by = auth.uid());

drop policy if exists "Site owners can update categories" on public.categories;
create policy "Site owners can update categories"
on public.categories
for update
to authenticated
using (public.is_site_owner())
with check (public.is_site_owner());

drop policy if exists "Site owners can delete categories" on public.categories;
create policy "Site owners can delete categories"
on public.categories
for delete
to authenticated
using (public.is_site_owner());

drop policy if exists "Visible posts are readable by everyone" on public.posts;
create policy "Visible posts are readable by everyone"
on public.posts
for select
to anon, authenticated
using (
  public.is_site_owner()
  or exists (
    select 1
    from public.categories
    where categories.id = posts.category_id
      and categories.is_visible = true
  )
);

drop policy if exists "Site owners can create posts" on public.posts;
create policy "Site owners can create posts"
on public.posts
for insert
to authenticated
with check (public.is_site_owner() and created_by = auth.uid());

drop policy if exists "Site owners can update posts" on public.posts;
create policy "Site owners can update posts"
on public.posts
for update
to authenticated
using (public.is_site_owner())
with check (public.is_site_owner());

drop policy if exists "Site owners can delete posts" on public.posts;
create policy "Site owners can delete posts"
on public.posts
for delete
to authenticated
using (public.is_site_owner());

grant select on public.categories to anon, authenticated;
grant insert, update, delete on public.categories to authenticated;
grant select on public.posts to anon, authenticated;
grant insert, update, delete on public.posts to authenticated;
grant usage on schema public to anon, authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter default privileges in schema public
  grant usage, select on sequences to authenticated;

commit;

-- Owner bootstrap:
-- 1. Sign up or create your account in Supabase Auth first.
-- 2. Replace the email below and run it once in the SQL editor.
--
-- insert into public.site_owners (user_id)
-- select id
-- from auth.users
-- where email = 'owner@example.com'
-- on conflict (user_id) do nothing;
